version: "3"

services:
  spring-service:
    image: spring-boot-proj3-jar
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql:5
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_database

  networks:
    my-network: